sonar.projectKey=Javier-Sinuka_bp
sonar.organization=javier-sinuka

sonar.projectName=nasa-bp
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Código fuente principal del repositorio BP.
# El proyecto se va a escanear con projectBaseDir=src/bp desde el workflow.
sonar.sources=fsw,psp_mod,dtn_defs,eds

# Unit tests del propio repo
sonar.tests=unit-test
sonar.test.inclusions=unit-test/**/*.c

# C/C++ analysis: lo genera Build Wrapper durante el build.
sonar.cfamily.compile-commands=../../build-wrapper-output/compile_commands.json

# Coverage C/C++ convertido por gcovr al formato genérico SonarQube.
sonar.coverageReportPaths=../../reports/coverage-sonarqube.xml

# Test execution convertido desde CTest/JUnit al formato genérico SonarQube.
sonar.testExecutionReportPaths=../../reports/test-execution.xml

# Exclusiones generales
sonar.exclusions=\
unit-test/**,\
docs/**,\
cosmos/**,\
config/**,\
.github/**,\
build/**,\
build-*/**,\
coverage/**,\
reports/**,\
**/*.md,\
**/*.txt

# No pedir coverage sobre tests, stubs ni definiciones auxiliares
sonar.coverage.exclusions=\
unit-test/**,\
**/stubs/**,\
**/utilities/**,\
docs/**,\
cosmos/**,\
config/**,\
dtn_defs/**,\
eds/**

# sonar.qualitygate.wait=true