sonar.projectKey=Javier-Sinuka_bp
sonar.organization=javier-sinuka

sonar.projectName=nasa-bp
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=fsw,psp_mod,dtn_defs,eds
sonar.tests=unit-test
sonar.test.inclusions=unit-test/**/*.c

sonar.cfamily.compile-commands=../../build-wrapper-output/compile_commands.json

sonar.coverageReportPaths=../../reports/coverage-sonarqube.xml
sonar.testExecutionReportPaths=../../reports/test-execution.xml

sonar.exclusions=\
unit-test/**,\
docs/**,\
cosmos/**,\
config/**,\
.github/**,\
build/**,\
build-*/**,\
coverage/**,\
reports/**,\
**/*.md,\
**/*.txt

sonar.coverage.exclusions=\
unit-test/**,\
**/stubs/**,\
**/utilities/**,\
docs/**,\
cosmos/**,\
config/**,\
dtn_defs/**,\
eds/**