# print_mib_counts_pkt.py
def print_mib_counts_pkt(target):
    print(f"target: {target}\n")
    
    pkt = "BPNODE_NODE_MIB_COUNTERS_HK"

    print("**************************************************************")
    print("************** BPNode Node MIB Counters HK *******************")
    print("**************************************************************")
    print("***  ADU_COUNT_DELIVERED                    :  ", tlm(f'{target} {pkt} ADU_COUNT_DELIVERED                    '))
    print("***  ADU_COUNT_RECEIVED                     :  ", tlm(f'{target} {pkt} ADU_COUNT_RECEIVED                     '))
    print("***  BUNDLE_AGENT_ACCEPTED_DIRECTIVE_COUNT  :  ", tlm(f'{target} {pkt} BUNDLE_AGENT_ACCEPTED_DIRECTIVE_COUNT  '))
    print("***  BUNDLE_AGENT_REJECTED_DIRECTIVE_COUNT  :  ", tlm(f'{target} {pkt} BUNDLE_AGENT_REJECTED_DIRECTIVE_COUNT  '))
    print("***  BUNDLE_COUNT_ABANDONED                 :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_ABANDONED                 '))
    print("***  BUNDLE_COUNT_ACCEPTED_CUSTODY          :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_ACCEPTED_CUSTODY          '))
    print("***  BUNDLE_COUNT_CCS_RECEIVED              :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_CCS_RECEIVED              ')) 
    print("***  BUNDLE_COUNT_CUSTODY_REJECTED          :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_CUSTODY_REJECTED          '))
    print("***  BUNDLE_COUNT_CUSTODY_REQUEST           :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_CUSTODY_REQUEST           '))
    print("***  BUNDLE_COUNT_CUSTODY_RE_FORWARDED      :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_CUSTODY_RE_FORWARDED      '))
    print("***  BUNDLE_COUNT_CUSTODY_TRANSFERRED       :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_CUSTODY_TRANSFERRED       '))
    print("***  BUNDLE_COUNT_DELETED                   :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED                   '))
    print("***  BUNDLE_COUNT_DELETED_EXPIRED           :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_EXPIRED           '))
    print("***  BUNDLE_COUNT_DELETED_HOP_EXCEEDED      :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_HOP_EXCEEDED      '))
    print("***  BUNDLE_COUNT_DELETED_NO_STORAGE        :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_NO_STORAGE        '))
    print("***  BUNDLE_COUNT_DELETED_TOO_LONG          :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_TOO_LONG          '))
    print("***  BUNDLE_COUNT_DELETED_TRAFFIC_PARED     :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_TRAFFIC_PARED     '))
    print("***  BUNDLE_COUNT_DELETED_UNAUTHORIZED      :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_UNAUTHORIZED      '))
    print("***  BUNDLE_COUNT_DELETED_UNINTELLIGIBLE    :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_UNINTELLIGIBLE    '))
    print("***  BUNDLE_COUNT_DELETED_UNSUPPORTED_BLOCK :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELETED_UNSUPPORTED_BLOCK '))
    print("***  BUNDLE_COUNT_DELIVERED                 :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DELIVERED                 '))
    print("***  BUNDLE_COUNT_DEPLETED                  :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DEPLETED                  '))
    print("***  BUNDLE_COUNT_DISCARDED                 :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_DISCARDED                 '))
    print("***  BUNDLE_COUNT_FORWARDED                 :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_FORWARDED                 '))
    print("***  BUNDLE_COUNT_FORWARDED_FAILED          :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_FORWARDED_FAILED          '))
    print("***  BUNDLE_COUNT_GENERATED_ACCEPTED        :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_GENERATED_ACCEPTED        '))
    print("***  BUNDLE_COUNT_GENERATED_REJECTED        :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_GENERATED_REJECTED        '))
    print("***  BUNDLE_COUNT_GENERATED_CUSTODY_SIGNAL  :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_GENERATED_CUSTODY_SIGNAL  '))    
    print("***  BUNDLE_COUNT_GENERATED_REJECTED        :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_GENERATED_REJECTED        '))
    print("***  BUNDLE_COUNT_MAX_BSR_RATE_EXCEEDED     :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_MAX_BSR_RATE_EXCEEDED     '))
    print("***  BUNDLE_COUNT_NO_CONTACT                :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_NO_CONTACT                '))
    print("***  BUNDLE_COUNT_NO_ROUTE                  :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_NO_ROUTE                  '))
    print("***  BUNDLE_COUNT_REASSEMBLED               :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_REASSEMBLED               '))
    print("***  BUNDLE_COUNT_RECEIVED                  :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_RECEIVED                  '))
    print("***  BUNDLE_COUNT_RECEIVED_ADMIN_RECORD     :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_RECEIVED_ADMIN_RECORD     '))
    print("***  BUNDLE_COUNT_RECEIVED_CUSTODY_SIGNAL   :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_RECEIVED_CUSTODY_SIGNAL   '))
    print("***  BUNDLE_COUNT_REDUNDANT                 :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_REDUNDANT                 '))
    print("***  BUNDLE_COUNT_REJECTED_CUSTODY          :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_REJECTED_CUSTODY          '))
    print("***  BUNDLE_COUNT_UNINTELLIGIBLE_BLOCK      :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_UNINTELLIGIBLE_BLOCK      '))
    print("***  BUNDLE_COUNT_UNINTELLIGIBLE_EID        :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_UNINTELLIGIBLE_EID        '))
    print("***  BUNDLE_COUNT_UNPROCESSED_BLOCKS        :  ", tlm(f'{target} {pkt} BUNDLE_COUNT_UNPROCESSED_BLOCKS        '))
    print("**************************************************************")
